### ISSUE TITLE
Add more .lang files

### ISSUE THREAD

**Issue by osiewicz** [PiotrOsiewicz/TicTacToe-C#2]
You can base new translations on .en_gb.lang.

**Comment by marcosinger** [comment]
@PiotrOsiewicz I could add a pt-BR lang file. Do you think it's good enough to get this PR merged?
An alternative could be create a new specific PR just for that.. yay or nah? :)

**Comment by rafaelkalan** [comment]
Pt-Br Done #4

**Comment by fragioli** [comment]
Added it-IT lang file #6

**Comment by osiewicz** [comment]
Yeah, feel free to make separate pull requests. It's fine with me. Keep in mind that @rafaelkalan has already done pt-br language. Take a look at it if you want.

**Comment by osiewicz** [comment]
Closing this for now. See: https://osiewicz.github.io/2018/10/15/Language-barriers.html
